/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **json_cache**
   * - Table in database
   */
  export namespace json_cache {
    export type Table = 'json_cache';
    export interface Selectable {
      /**
      * **json_cache.key**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      key: string;
      /**
      * **json_cache.value**
      * - `jsonb` in database
      * - Nullable, no default
      */
      value: db.JSONValue | null;
      /**
      * **json_cache.stored_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      stored_at: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **json_cache.key**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      key: string;
      /**
      * **json_cache.value**
      * - `jsonb` in database
      * - Nullable, no default
      */
      value: db.JSONValue | null;
      /**
      * **json_cache.stored_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      stored_at: db.TimestampString | null;
    }
    export interface Whereable {
      /**
      * **json_cache.key**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      key?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **json_cache.value**
      * - `jsonb` in database
      * - Nullable, no default
      */
      value?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **json_cache.stored_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      stored_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **json_cache.key**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      key: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **json_cache.value**
      * - `jsonb` in database
      * - Nullable, no default
      */
      value?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **json_cache.stored_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      stored_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **json_cache.key**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      key?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **json_cache.value**
      * - `jsonb` in database
      * - Nullable, no default
      */
      value?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **json_cache.stored_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      stored_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'pk_json_cache';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = json_cache.Table;
    export type Selectable = json_cache.Selectable;
    export type JSONSelectable = json_cache.JSONSelectable;
    export type Whereable = json_cache.Whereable;
    export type Insertable = json_cache.Insertable;
    export type Updatable = json_cache.Updatable;
    export type UniqueIndex = json_cache.UniqueIndex;
    export type Column = json_cache.Column;
  
    export type AllBaseTables = [json_cache.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [json_cache.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "json_cache": json_cache.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "json_cache": json_cache.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "json_cache": json_cache.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "json_cache": json_cache.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "json_cache": json_cache.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "json_cache": json_cache.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "json_cache": json_cache.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "json_cache": json_cache.SQL;
  }[T];

}
